name: AritmeticExpression
version: 0.1.0.0
github: "DMichelR/AritmeticExpression"
license: BSD-3-Clause
author: "Diego Michel Roca"
maintainer: "aa6132788@gmail.com"
copyright: "2024 Diego Michel Roca"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
  - base >= 4.7 && < 5
  - parsec

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  AritmeticExpression-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AritmeticExpression

tests:
  AritmeticExpression-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AritmeticExpression
